apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: backend
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-example
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: backend
    spec:
      containers:
        image: issac04/backend
        name: backend
        port:
          - containerPort: 5000
      restartPolicy: Always
