apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: backend
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-example
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: backend
    spec:
      containers:
      - image: issac04/backend
        name: backend
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"  # Set CPU limit to 500 millicpu
            memory: "512Mi"  # Set memory limit to 512 Mebibytes
          requests:
            cpu: "100m"  # Request 100 millicpu
            memory: "256Mi"  # Request 256 Mebibytes
      restartPolicy: Always
