apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: backend
  namespace: kube-system
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: microservice-app-example
    service: backend
