FROM golang:alpine3.17 as build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o backend .

FROM alpine:3.11.3
WORKDIR /app
COPY --from=build /app .
EXPOSE 5000
CMD [ "./backend" ]