apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: pg-db
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-example
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: pg-db
    spec:
      containers:
        - name: pg-db
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "8242"
            - name: POSTGRES_DB
              value: whitelake
